sonar.projectKey=JeanSaltos_ParkingApp
sonar.organization=jeansaltos
sonar.projectName=ParkingApp
sonar.sourceEncoding=UTF-8

sonar.sources=usuarios/src/main/java,zonas-espacios/src/main/java,vehiqlos/src,tickets/src
sonar.tests=usuarios/src/test/java,zonas-espacios/src/test/java,vehiqlos/test,tickets/test

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/coverage/**,**/*.spec.ts,**/*.e2e-spec.ts
sonar.test.inclusions=**/*Test.java,**/*.spec.ts,**/*.e2e-spec.ts

sonar.java.binaries=usuarios/target/classes,zonas-espacios/target/classes
sonar.javascript.lcov.reportPaths=vehiqlos/coverage/lcov.info,tickets/coverage/lcov.info
